name: flutter_template
description: "A new Flutter project."
organization: com.example
version: 1.0.0+1
platform: 'android,windows,linux,macos,web'
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # 专门处理yaml文件
  yaml_magic: ^1.0.6
  # 代码生成，运行自动化任务的工具
  build_runner: ^2.4.11
  # 将资源文件映射成代码
  flutter_gen_runner: ^5.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/
