name: Flutter

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: FlutterAction
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 下载依赖
        run: flutter pub get


      - name: 打包安卓
        run: flutter build apk
        env:
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: 打包Macos
        run: flutter build macos

      - name: 获取版本号
        run: |
          echo "version=$(awk -F': ' '/version:/ {gsub("\\+", "-", $2); print $2}' pubspec.yaml)" >> "$GITHUB_ENV"

      - name: 打印版本号
        run: |
          echo "version: ${{ env.version }}"

      - name: Release apk
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ env.version }}"
          draft: false
          artifacts: "build/app/outputs/flutter-apk/*, build/macos/Build/Products/Release/flutter_template.app"
          allowUpdates: true
          generateReleaseNotes: true
          token: ${{ secrets.TOKEN }}

      - name: 打包Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: 部署到Github Page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          branch: gh-pages
          folder: build/web
          clean: true